[window]
decorations="None"
dimensions.columns=158
dimensions.lines=57
position.x=576

[font]
size=12.0
[font.bold]
family="DroidSansM Nerd Font Mono"
style="Bold"
[font.bold_italic]
family="DroidSansM Nerd Font Mono"
style="Bold Italic"
[font.italic]
family="DroidSansM Nerd Font Mono"
style="Italic"
[font.normal]
family="DroidSansM Nerd Font Mono"
style="Regular"

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
